CREATE TABLE IF NOT EXISTS FOOTERS
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    signature VARCHAR                                 NOT NULL,
    city      VARCHAR                                 NOT NULL,
    year      VARCHAR                                 NOT NULL,
    CONSTRAINT pk_footer PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS LICENSE
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    division VARCHAR                                 NOT NULL,
    license  VARCHAR                                 NOT NULL,
    CONSTRAINT pk_license PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS TEXT_CENTERED
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    report_name VARCHAR                                 NOT NULL,
    text_first  VARCHAR                                 NOT NULL,
    object      VARCHAR                                 NOT NULL,
    text_second VARCHAR                                 NOT NULL,
    address     VARCHAR                                 NOT NULL,
    CONSTRAINT pk_textCentered PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS TITLE_HEADERS
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type   VARCHAR                                 NOT NULL,
    name   VARCHAR                                 NOT NULL,
    branch VARCHAR                                 NOT NULL,
    CONSTRAINT pk_titleHeader PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS TITLES
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    header_id  BIGINT                                  NOT NULL,
    license_id BIGINT                                  NOT NULL,
    text_id    BIGINT                                  NOT NULL,
    footer_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_title PRIMARY KEY (id),
    CONSTRAINT FK_TITLES_ON_TITLE_HEADERS FOREIGN KEY (header_id) REFERENCES title_headers (id),
    CONSTRAINT FK_TITLES_ON_LICENSES FOREIGN KEY (license_id) REFERENCES license (id),
    CONSTRAINT FK_TITLES_ON_TEXT_CENTERED FOREIGN KEY (text_id) REFERENCES text_centered (id),
    CONSTRAINT FK_TITLES_ON_FOOTERS FOREIGN KEY (footer_id) REFERENCES footers (id)
);