CREATE TABLE IF NOT EXISTS EDGES
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    thickness INTEGER                                 NOT NULL,
    min       FLOAT                                   NOT NULL,
    CONSTRAINT pk_edge PRIMARY KEY (id),
    CONSTRAINT UQ_EDGES UNIQUE (thickness)
);

CREATE TABLE IF NOT EXISTS BOTTOMS
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_id   BIGINT                                  NOT NULL,
    volume    INTEGER                                 NOT NULL,
    name      VARCHAR,
    thickness INTEGER                                 NOT NULL,
    min       FLOAT                                   NOT NULL,
    edge_id   BIGINT,
    CONSTRAINT pk_bottom PRIMARY KEY (id),
    CONSTRAINT UQ_BOTTOMS UNIQUE (volume, thickness),
    CONSTRAINT FK_BOTTOMS_ON_EDGES FOREIGN KEY (edge_id) REFERENCES edges (id)
);

CREATE TABLE IF NOT EXISTS BELTS
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_id   BIGINT                                  NOT NULL,
    volume    INTEGER                                 NOT NULL,
    number    INTEGER                                 NOT NULL,
    thickness INTEGER                                 NOT NULL,
    min       FLOAT                                   NOT NULL,
    CONSTRAINT pk_belt PRIMARY KEY (id),
    CONSTRAINT UQ_BELTS UNIQUE (number, thickness, volume)
);

CREATE TABLE IF NOT EXISTS PIPELINE_NORMS
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_id   BIGINT                                  NOT NULL,
    diameter  INTEGER                                 NOT NULL,
    thickness FLOAT                                   NOT NULL,
    min       FLOAT                                   NOT NULL,
    CONSTRAINT pk_pipelineNorm PRIMARY KEY (id),
    CONSTRAINT UQ_PIPELINE_NORMS UNIQUE (type_id, diameter, thickness)
);

CREATE TABLE IF NOT EXISTS PASSPORTS
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_id        BIGINT,
    object_data_id BIGINT,
    CONSTRAINT pk_passport PRIMARY KEY (id),
    CONSTRAINT UQ_PASSPORTS UNIQUE (object_data_id)
);

CREATE TABLE IF NOT EXISTS SURVEYS
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date            DATE                                    NOT NULL,
    survey          VARCHAR                                 NOT NULL,
    number          VARCHAR                                 NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    passport_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_survey PRIMARY KEY (id),
    CONSTRAINT UQ_SURVEYS UNIQUE (date, survey, number, organization_id),
    CONSTRAINT FK_SURVEYS_ON_PASSPORTS FOREIGN KEY (passport_id) REFERENCES passports (id)
);

CREATE TABLE IF NOT EXISTS PASSPORTS_SURVEYS
(
    passport_id BIGINT,
    survey_id   BIGINT,
    CONSTRAINT pk_passport_of_surveys PRIMARY KEY (passport_id, survey_id)
);

CREATE TABLE IF NOT EXISTS REPAIRS
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date            DATE                                    NOT NULL,
    description     VARCHAR                                 NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    passport_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_repair PRIMARY KEY (id),
    CONSTRAINT UQ_REPAIRS UNIQUE (date, description, organization_id),
    CONSTRAINT FK_REPAIRS_ON_PASSPORTS FOREIGN KEY (passport_id) REFERENCES passports (id)
);

CREATE TABLE IF NOT EXISTS PASSPORTS_REPAIRS
(
    passport_id BIGINT,
    repair_id   BIGINT,
    CONSTRAINT pk_passport_of_repairs PRIMARY KEY (passport_id, repair_id)
);

CREATE TABLE IF NOT EXISTS CHARACTERISTICS
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subheading_id BIGINT                                  NOT NULL,
    meaning       VARCHAR                                 NOT NULL,
    passport_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_characteristic PRIMARY KEY (id),
    CONSTRAINT FK_CHARACTERISTICS_ON_PASSPORTS FOREIGN KEY (passport_id) REFERENCES passports (id)
);

CREATE TABLE IF NOT EXISTS NORMS
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_data_id BIGINT                                  NOT NULL,
    type_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_norm PRIMARY KEY (id),
    CONSTRAINT UQ_NORMS UNIQUE (object_data_id)
);

CREATE TABLE IF NOT EXISTS NORMS_BELTS
(
    norm_id BIGINT,
    belt_id BIGINT,
    CONSTRAINT pk_norm_of_belts PRIMARY KEY (norm_id, belt_id)
);

CREATE TABLE IF NOT EXISTS NORMS_BOTTOMS
(
    norm_id   BIGINT,
    bottom_id BIGINT,
    CONSTRAINT pk_norm_of_bottoms PRIMARY KEY (norm_id, bottom_id)
);

CREATE TABLE IF NOT EXISTS NORMS_PIPELINE_NORMS
(
    norm_id          BIGINT,
    pipeline_norm_id BIGINT,
    CONSTRAINT pk_norm_of_pipeline_norms PRIMARY KEY (norm_id, pipeline_norm_id)
);